version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ducklake-postgres
    environment:
      POSTGRES_DB: ducklake_catalog
      POSTGRES_USER: ducklake
      POSTGRES_PASSWORD: ducklake123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ducklake -d ducklake_catalog"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local